name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-22.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: install rst-lint
      run: |
        python -m pip install restructuredtext-lint pygments
    - name: check README syntax
      run: |
        rst-lint --level=info --encoding=UTF-8 README
    - run: |
        perl --version
    - name: install perlcritic
      run: |
        sudo apt-get install libperl-critic-perl
    - name: run perlcritic
      run: |
        perlcritic $(grep -rl '/env perl$' .)
    - name: install deps
      run:
        sudo apt-get install libio-socket-ssl-perl libhttp-cookiejar-perl
    - name: run tests
      run: |
        PACZ_NETWORK_TESTING=1 prove -v

# vim:ts=2 sts=2 sw=2 et
