name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: install rst-lint
      run: |
        python -m pip install pygments restructuredtext-lint
    - name: check README syntax
      run: |
        rst-lint --level=info --encoding=UTF-8 README
    - run: |
        perl --version
    - name: install perlcritic
      run: |
        sudo apt-get install libperl-critic-perl
    - name: run perlcritic
      run: |
        perlcritic $(grep -rl '/env perl$' .)
    - name: install HTTP::CookieJar
      run:
        sudo apt-get install libhttp-cookiejar-perl
    - name: run tests
      run: |
        PACZ_NETWORK_TESTING=1 prove -v

# vim:ts=2 sts=2 sw=2 et
